apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s58vzfqbs-python 
  janus-idp.io/tekton: s58vzfqbs-python
  backstage.io/kubernetes-id: s58vzfqbs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s58vzfqbs-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  