apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s58vzfqbs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s58vzfqbs-python 
  name: s58vzfqbs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s58vzfqbs-python 
